name: efp_base_macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: CMake set-up
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: make
