name: efp_base_win

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install gtest
      uses: MarkusJx/googletest-installer@v1.1
    - uses: actions/checkout@v2
    - name: CMake set-up
      run: cmake -S . `-D CMAKE_BUILD_TYPE=Release`
    - name: make
      run: cmake --build . --config Release
