name: unit_tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GTest
      run: sudo apt install libgtest-dev
    - name: CMake set-up
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: Build
      run: cmake --build . --config Release --target runUnitTestsEFP
    - name: Run tests
      run: ./runUnitTestsEFP
